import { z } from "zod";
import { AccountIdSchema } from "./account";

/**
 * A movement of money on a single date. Either side may be external:
 * income has no source account, spending has no destination account.
 * Transfers don't replace balance snapshots — recording one derives new
 * snapshots on the affected accounts so the charts stay truthful.
 */
export const TransferSchema = z
  .object({
    id: z.string().min(1),
    date: z.iso.date(),
    fromAccountId: AccountIdSchema.optional(),
    toAccountId: AccountIdSchema.optional(),
    amount: z.number().positive("Amount must be positive"),
    /** Native amount removed from the source for a cross-currency transfer. */
    fromAmount: z.number().positive().optional(),
    /** Native amount added to the destination for a cross-currency transfer. */
    toAmount: z.number().positive().optional(),
    /** Fee charged in the source account's native currency. */
    feeAmount: z.number().nonnegative().optional(),
    /** Bank, broker, or service that performed the conversion. */
    conversionProvider: z.string().min(1).optional(),
    /** Set when this transfer was generated by materialising a recurring flow */
    flowId: z.string().min(1).optional(),
  })
  .refine((t) => t.fromAccountId != null || t.toAccountId != null, {
    message: "A transfer needs a source or a destination account",
  })
  .refine((t) => t.fromAccountId !== t.toAccountId, {
    message: "Source and destination must differ",
  });

export type Transfer = z.infer<typeof TransferSchema>;

export function transferAmountFrom(transfer: Transfer): number {
  return transfer.fromAmount ?? transfer.amount;
}

export function transferAmountTo(transfer: Transfer): number {
  return transfer.toAmount ?? transfer.amount;
}

export function transferFeeAmount(transfer: Transfer): number {
  return transfer.feeAmount ?? 0;
}
