export type WorkGraphErrorCode =
  | "attention_request_already_resolved"
  | "attention_request_not_found"
  | "dependency_already_exists"
  | "decomposition_child_not_claimable"
  | "dependency_not_found"
  | "duplicate_attention_request"
  | "duplicate_attention_resolution"
  | "duplicate_architecture_decision"
  | "duplicate_context"
  | "duplicate_lease_id"
  | "duplicate_note"
  | "duplicate_reference"
  | "duplicate_pull_request"
  | "duplicate_work_item_pull_request"
  | "duplicate_work_item"
  | "graph_cycle"
  | "idempotency_key_reused"
  | "invalid_attention_kind"
  | "invalid_attention_question"
  | "invalid_attention_request_id"
  | "invalid_attention_resolution"
  | "invalid_attention_resolution_id"
  | "invalid_architecture_decision_role"
  | "invalid_architecture_decision_title"
  | "invalid_child_rank"
  | "invalid_claim_scope"
  | "invalid_completion_evidence"
  | "invalid_context_content"
  | "invalid_context_kind"
  | "invalid_context_url"
  | "invalid_decomposition"
  | "invalid_idempotency_key"
  | "invalid_knowledge_scope_id"
  | "invalid_knowledge_scope_kind"
  | "invalid_knowledge_scope_lifecycle"
  | "invalid_knowledge_scope_archive_reason"
  | "invalid_knowledge_scope_rank"
  | "invalid_knowledge_scope_relationship_cursor"
  | "invalid_knowledge_scope_source_revision"
  | "invalid_knowledge_scope_title"
  | "invalid_knowledge_scope_url"
  | "invalid_lease_duration"
  | "invalid_lease_epoch"
  | "invalid_lease_id"
  | "invalid_note_content"
  | "invalid_note_author"
  | "invalid_note_id"
  | "invalid_parent_id"
  | "invalid_worker_id"
  | "invalid_work_item_id"
  | "invalid_work_item_dependency_cursor"
  | "invalid_work_item_lifecycle"
  | "invalid_priority_move"
  | "invalid_priority_rank"
  | "invalid_reference_title"
  | "invalid_pull_request"
  | "invalid_pull_request_role"
  | "pull_request_not_found"
  | "invalid_scheduling_scope"
  | "invalid_expedite_reason"
  | "invalid_work_item_title"
  | "lease_not_current"
  | "knowledge_scope_cycle"
  | "knowledge_scope_has_open_work"
  | "knowledge_scope_not_found"
  | "knowledge_scope_relationship_already_exists"
  | "knowledge_scope_relationship_not_found"
  | "self_dependency"
  | "work_item_already_terminal"
  | "work_item_has_current_lease"
  | "work_item_not_released"
  | "work_item_not_found";

export class WorkGraphError extends Error {
  readonly code: WorkGraphErrorCode;

  constructor(code: WorkGraphErrorCode, message: string) {
    super(message);
    this.name = "WorkGraphError";
    this.code = code;
  }
}
