import type { RecurringFlow } from "@/lib/domain/assettracker/recurringFlow";

export const recurringFlows: RecurringFlow[] = [
  {
    id: "salary",
    name: "Household take-home pay",
    toAccountId: "nationwide-current",
    amount: 6635.33,
    grossAmount: 8333.33,
    currency: "GBP",
    compensationKind: "takeHomeIncome",
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "freelance-invoices",
    name: "Freelance invoices",
    toAccountId: "nationwide-current",
    amount: 650,
    currency: "GBP",
    compensationKind: "sideIncome",
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "isa-contribution",
    name: "ISA contribution",
    fromAccountId: "nationwide-current",
    toAccountId: "trading-212-isa",
    amount: 500,
    currency: "GBP",
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "pension-contribution",
    name: "Pension contribution",
    fromAccountId: "nationwide-current",
    toAccountId: "workplace-pension",
    amount: 666.67,
    currency: "GBP",
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "pension-tax-relief",
    name: "Pension tax relief",
    toAccountId: "workplace-pension",
    amount: 166.67,
    currency: "GBP",
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "us-brokerage-contribution",
    name: "US brokerage contribution",
    fromAccountId: "nationwide-current",
    toAccountId: "us-brokerage",
    amount: 300,
    currency: "GBP",
    conversion: {
      received: { amount: 380, currency: "USD" },
      fee: { amount: 2, currency: "GBP" },
      provider: "Wise",
    },
    frequency: "monthly",
    startDate: "2024-01-01",
  },
  {
    id: "mortgage-payment",
    name: "Mortgage payment",
    fromAccountId: "nationwide-current",
    toAccountId: "home-mortgage",
    amount: 1150,
    currency: "GBP",
    frequency: "monthly",
    startDate: "2023-03-01",
  },
  {
    id: "amex-minimum-payment",
    name: "Amex minimum payment",
    fromAccountId: "nationwide-current",
    toAccountId: "amex-credit-card",
    // Greater of 2.5% of the outstanding balance or £25
    formula: { kind: "minimumPayment", percentOfBalance: 0.025, floor: 25 },
    currency: "GBP",
    frequency: "monthly",
    startDate: "2023-06-01",
  },
];
