import type { SalaryHistoryRecord } from "@/lib/domain/assettracker/salaryHistory";

const importedSource = (row: number) => ({
  kind: "file" as const,
  fileName: "salary-history-demo.csv",
  fingerprint: "demo-salary-history-v1",
  row,
});

/**
 * Synthetic salary facts covering job changes, raises, an employment gap,
 * part-time period pay, variable pay, pension changes, and a correction.
 */
export const salaryHistory: SalaryHistoryRecord[] = [
  {
    id: "alex-northstar-2020",
    person: "Alex",
    employer: "Northstar Studio",
    employmentId: "alex-northstar",
    currency: "GBP",
    jurisdiction: "England and Wales",
    effectiveStart: "2020-01-01",
    effectiveEnd: "2021-08-31",
    payFrequency: "monthly",
    amountKind: "annualSalary",
    grossPay: 42_000,
    baseSalary: 42_000,
    variablePay: 0,
    employeePension: {
      arrangement: "netPay",
      rate: 0.05,
      basis: "qualifyingEarnings",
      effectiveStart: "2020-01-01",
      effectiveEnd: "2021-08-31",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.03,
      basis: "qualifyingEarnings",
      effectiveStart: "2020-01-01",
      effectiveEnd: "2021-08-31",
    },
    source: importedSource(2),
    acceptedAt: "2025-01-10T09:00:00.000Z",
  },
  {
    id: "alex-northstar-2021-raise",
    person: "Alex",
    employer: "Northstar Studio",
    employmentId: "alex-northstar",
    currency: "GBP",
    jurisdiction: "England and Wales",
    effectiveStart: "2021-09-01",
    effectiveEnd: "2022-06-30",
    payFrequency: "monthly",
    amountKind: "annualSalary",
    grossPay: 47_000,
    baseSalary: 47_000,
    variablePay: 0,
    taxablePay: 47_000,
    employeePension: {
      arrangement: "salarySacrifice",
      rate: 0.06,
      basis: "grossPay",
      effectiveStart: "2021-09-01",
      effectiveEnd: "2022-06-30",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.04,
      basis: "grossPay",
      effectiveStart: "2021-09-01",
      effectiveEnd: "2022-06-30",
    },
    source: importedSource(3),
    acceptedAt: "2025-01-10T09:00:01.000Z",
  },
  {
    id: "sam-fieldwork-part-time",
    person: "Sam",
    employer: "Fieldwork Co-op",
    employmentId: "sam-fieldwork",
    currency: "GBP",
    jurisdiction: "Scotland",
    effectiveStart: "2021-04-01",
    effectiveEnd: "2023-03-31",
    payFrequency: "monthly",
    amountKind: "periodPay",
    workFraction: 0.8,
    grossPay: 3_200,
    baseSalary: 3_000,
    variablePay: 200,
    taxablePay: 3_040,
    takeHomePay: 2_480,
    employeePension: {
      arrangement: "salarySacrifice",
      amount: 160,
      basis: "grossPay",
      effectiveStart: "2021-04-01",
      effectiveEnd: "2023-03-31",
    },
    employerPension: {
      arrangement: "other",
      amount: 128,
      basis: "grossPay",
      effectiveStart: "2021-04-01",
      effectiveEnd: "2023-03-31",
    },
    source: importedSource(4),
    acceptedAt: "2025-01-10T09:00:02.000Z",
  },
  {
    id: "alex-cirrus-2022",
    person: "Alex",
    employer: "Cirrus Systems",
    employmentId: "alex-cirrus",
    currency: "GBP",
    jurisdiction: "England and Wales",
    effectiveStart: "2022-09-01",
    effectiveEnd: "2024-03-31",
    payFrequency: "monthly",
    amountKind: "annualSalary",
    grossPay: 65_000,
    baseSalary: 60_000,
    variablePay: 5_000,
    taxablePay: 61_100,
    takeHomePay: 43_800,
    employeePension: {
      arrangement: "salarySacrifice",
      rate: 0.06,
      basis: "grossPay",
      effectiveStart: "2022-09-01",
      effectiveEnd: "2024-03-31",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.06,
      basis: "grossPay",
      effectiveStart: "2022-09-01",
      effectiveEnd: "2024-03-31",
    },
    source: importedSource(5),
    acceptedAt: "2025-01-10T09:00:03.000Z",
  },
  {
    id: "sam-fieldwork-full-time",
    person: "Sam",
    employer: "Fieldwork Co-op",
    employmentId: "sam-fieldwork",
    currency: "GBP",
    jurisdiction: "Scotland",
    effectiveStart: "2023-04-01",
    payFrequency: "annual",
    amountKind: "annualSalary",
    workFraction: 1,
    grossPay: 52_000,
    baseSalary: 48_000,
    variablePay: 4_000,
    taxablePay: 49_400,
    takeHomePay: 36_600,
    employeePension: {
      arrangement: "netPay",
      rate: 0.05,
      basis: "pensionablePay",
      effectiveStart: "2023-04-01",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.05,
      basis: "pensionablePay",
      effectiveStart: "2023-04-01",
    },
    source: importedSource(6),
    acceptedAt: "2025-01-10T09:00:04.000Z",
  },
  {
    id: "alex-cirrus-2024-original",
    person: "Alex",
    employer: "Cirrus Systems",
    employmentId: "alex-cirrus",
    currency: "GBP",
    jurisdiction: "England and Wales",
    effectiveStart: "2024-04-01",
    payFrequency: "monthly",
    amountKind: "annualSalary",
    grossPay: 70_000,
    baseSalary: 62_000,
    variablePay: 8_000,
    taxablePay: 65_800,
    takeHomePay: 46_100,
    employeePension: {
      arrangement: "salarySacrifice",
      rate: 0.06,
      basis: "grossPay",
      effectiveStart: "2024-04-01",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.08,
      basis: "grossPay",
      effectiveStart: "2024-04-01",
    },
    source: importedSource(7),
    acceptedAt: "2025-01-10T09:00:05.000Z",
  },
  {
    id: "alex-cirrus-2024-corrected",
    person: "Alex",
    employer: "Cirrus Systems",
    employmentId: "alex-cirrus",
    currency: "GBP",
    jurisdiction: "England and Wales",
    effectiveStart: "2024-04-01",
    payFrequency: "monthly",
    amountKind: "annualSalary",
    grossPay: 72_000,
    baseSalary: 64_000,
    variablePay: 8_000,
    taxablePay: 67_680,
    takeHomePay: 47_300,
    employeePension: {
      arrangement: "salarySacrifice",
      rate: 0.06,
      basis: "grossPay",
      effectiveStart: "2024-04-01",
    },
    employerPension: {
      arrangement: "other",
      rate: 0.08,
      basis: "grossPay",
      effectiveStart: "2024-04-01",
    },
    source: { kind: "manual" },
    acceptedAt: "2025-01-11T10:30:00.000Z",
    correctsId: "alex-cirrus-2024-original",
  },
];
