apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes-retain
provisioner: csi.hetzner.cloud
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
