query WorkGraphPools(
  $accountTag: string!
  $configId: string!
  $start: Time!
  $end: Time!
) {
  viewer {
    accounts(filter: { accountTag: $accountTag }) {
      hyperdrivePoolSizesAdaptiveGroups(
        limit: 10000
        filter: {
          configId: $configId
          datetime_geq: $start
          datetime_leq: $end
        }
      ) {
        avg {
          currentPoolSize
          availablePoolSlots
          waitingClients
        }
        max {
          maxPoolSize
          currentPoolSize
          waitingClients
        }
        dimensions {
          coloCode
        }
      }
      hyperdriveQueriesAdaptiveGroups(
        limit: 10000
        filter: {
          configId: $configId
          datetime_geq: $start
          datetime_leq: $end
          eventStatus: "error"
        }
      ) {
        count
      }
    }
  }
}
